# Generated by Django 3.2.13 on 2022-06-05 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.CharField(blank=True, max_length=255)),
                ('contract_no', models.CharField(max_length=15)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('contract_type', models.CharField(blank=True, max_length=255)),
                ('poc_name', models.CharField(max_length=255)),
                ('poc_number', models.CharField(max_length=100)),
                ('poc_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('dev_cond', models.CharField(blank=True, max_length=255)),
                ('dev_dec', models.CharField(blank=True, max_length=255)),
                ('dev_qty', models.IntegerField(blank=True, null=True)),
                ('dev_amnt', models.IntegerField(blank=True, null=True)),
                ('dev_amnt_totl', models.IntegerField(blank=True, null=True)),
                ('other_service', models.CharField(blank=True, max_length=255)),
                ('other_dec', models.CharField(blank=True, max_length=255)),
                ('other_pay_method', models.CharField(blank=True, max_length=255)),
                ('other_qty', models.IntegerField(blank=True, null=True)),
                ('other_price', models.IntegerField(blank=True, null=True)),
                ('payment_total', models.IntegerField(blank=True, null=True)),
                ('service_charge', models.IntegerField(blank=True, null=True)),
                ('other_charges', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customerDevices', models.ManyToManyField(blank=True, to='core.CustomerDevice')),
                ('packages', models.ManyToManyField(blank=True, to='core.Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
