# Generated by Django 4.2.2 on 2023-06-11 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='activation',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 11, 20, 51, 173191)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 11, 20, 51, 173191)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 11, 20, 51, 173191)),
        ),
    ]
