# Generated by Django 4.1.5 on 2023-08-02 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contracts_activation_alter_contracts_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='activation',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 12, 44, 944227)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 12, 44, 944202)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 11, 12, 44, 944243)),
        ),
    ]
