# Generated by Django 3.2.13 on 2022-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220629_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ann_collected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cable_collected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cable_cond',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='rou_collected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
