# Generated by Django 4.2.2 on 2023-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contracts_activation_alter_contracts_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdetails',
            name='access_point',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='cable',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='ccq',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='connector',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='payment',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='signal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
