# Generated by Django 3.2.13 on 2022-07-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220629_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('done', 'Done'), ('in-progress', 'In-Progress'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=15),
        ),
    ]
