# Generated by Django 3.2.13 on 2022-07-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='curren',
            field=models.CharField(blank=True, default='Afs', max_length=5),
        ),
    ]
