# Generated by Django 3.2.14 on 2022-07-14 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contract_curren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='antenna',
        ),
        migrations.AddField(
            model_name='contract',
            name='antenna',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='packages',
        ),
        migrations.AddField(
            model_name='contract',
            name='packages',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='router',
        ),
        migrations.AddField(
            model_name='contract',
            name='router',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=255)),
                ('log', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
