# Generated by Django 3.2.14 on 2022-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220714_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='package_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
