# Generated by Django 3.2.14 on 2022-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contract_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ann_lease_amnt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='rou_lease_amnt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
