# Generated by Django 3.2.14 on 2022-07-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220714_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Contract_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='activation_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='contract',
            name='valid_upto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
