# Generated by Django 3.2.14 on 2022-07-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220721_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='lease_deposit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
