# Generated by Django 3.2.14 on 2022-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contract_lease_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Contract_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='activation_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ann_cond',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ann_dec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ann_lease_amnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cable_cond',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='curren',
            field=models.CharField(blank=True, default='AFN', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='other_dec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='other_pay_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='other_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='package_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='poc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='poc_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='poc_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rou_cond',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rou_dec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rou_lease_amnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('done', 'Done'), ('in-progress', 'In-Progress'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
