# Generated by Django 3.2.14 on 2022-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220721_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='package_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
