# Generated by Django 3.2.14 on 2022-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_contract_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='antenna',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='packages',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='router',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
