# Generated by Django 3.2.14 on 2022-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220721_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='curren',
            field=models.CharField(blank=True, default='AFN', max_length=255, null=True),
        ),
    ]
