# Generated by Django 3.2.14 on 2022-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220726_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='rou_qty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
