# Generated by Django 3.2.14 on 2022-07-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_contract_rou_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Contract_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
