# Generated by Django 3.2.14 on 2022-07-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220731_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Contract_date',
            field=models.DateTimeField(null=True),
        ),
    ]
