# Generated by Django 3.2.14 on 2022-07-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_contract_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
