# Generated by Django 3.2.14 on 2022-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_contract_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Contract_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
