# Generated by Django 3.2.14 on 2022-08-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220731_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='activation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(null=True),
        ),
    ]
