# Generated by Django 3.2.14 on 2022-08-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220801_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Contract_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
