# Generated by Django 3.2.14 on 2022-08-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_contract_contract_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='valid_upto',
        ),
    ]
