# Generated by Django 3.2.14 on 2022-08-09 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_contract_valid_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 23, 8, 573213)),
        ),
    ]
