# Generated by Django 3.2.14 on 2022-08-09 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_contract_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='activation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 27, 3, 999315)),
        ),
    ]
