# Generated by Django 3.2.14 on 2022-08-23 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220809_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='activation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 10, 8, 9, 106794)),
        ),
    ]
