# Generated by Django 3.2.14 on 2022-08-23 05:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220823_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='activation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 10, 11, 9, 357856)),
        ),
    ]
