# Generated by Django 3.2.14 on 2022-09-03 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220828_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 10, 24, 53, 409267)),
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 10, 24, 53, 404860)),
        ),
    ]
