# Generated by Django 3.2.14 on 2022-09-10 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20220903_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='label',
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='project',
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskmanagerlabels',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskmanagertags',
            name='user',
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 15, 48, 41, 870348)),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TaskManager',
        ),
        migrations.DeleteModel(
            name='TaskManagerLabels',
        ),
        migrations.DeleteModel(
            name='TaskManagerTags',
        ),
    ]
