# Generated by Django 3.2.14 on 2022-09-11 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_contract_valid_upto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable', models.BooleanField(default=False)),
                ('stand', models.BooleanField(default=False)),
                ('router', models.BooleanField(default=False)),
                ('antenna', models.BooleanField(default=False)),
                ('router_os', models.BooleanField(default=False)),
                ('signal', models.BooleanField(default=False)),
                ('dns', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_type', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=255)),
                ('access_point', models.CharField(max_length=10)),
                ('signal', models.CharField(max_length=10)),
                ('ccq', models.CharField(max_length=10)),
                ('cable', models.IntegerField()),
                ('connector', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('bill_number', models.IntegerField()),
                ('installation_date', models.DateTimeField()),
                ('additional_details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='installation',
            name='user',
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 16, 3, 13, 816072)),
        ),
        migrations.AlterField(
            model_name='installation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contract'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Troubleshoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=255)),
                ('service_charge', models.IntegerField()),
                ('description', models.TextField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.checklist')),
                ('link_derails', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkdetails')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('service_charge', models.IntegerField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.checklist')),
                ('link_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkdetails')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='link_derails',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkdetails'),
        ),
    ]
