# Generated by Django 3.2.14 on 2022-09-11 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_contract_valid_upto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installation',
            old_name='link_derails',
            new_name='link_details',
        ),
        migrations.RenameField(
            model_name='troubleshoot',
            old_name='link_derails',
            new_name='link_details',
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 16, 4, 25, 387731)),
        ),
    ]
