# Generated by Django 3.2.14 on 2022-09-11 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_contract_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 21, 48, 2, 800136)),
        ),
    ]
