# Generated by Django 3.2.14 on 2022-09-12 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_contract_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 12, 9, 52, 523559)),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.checklist'),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='link_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkdetails'),
        ),
    ]
