# Generated by Django 3.2.14 on 2022-09-12 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20220912_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 12, 11, 48, 441387)),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.checklist'),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='link_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkdetails'),
        ),
    ]
