# Generated by Django 3.2.14 on 2022-09-12 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220912_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 12, 20, 3, 875166)),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='access_point',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='bill_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='cable',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='ccq',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='connector',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='installation_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='installation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='payment',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='signal',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
