# Generated by Django 3.2.15 on 2022-09-19 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20220913_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 11, 4, 11, 644919)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 11, 4, 11, 644919)),
        ),
        migrations.AlterField(
            model_name='installation',
            name='link_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkdetails'),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 11, 4, 11, 651106)),
        ),
    ]
