# Generated by Django 3.2.15 on 2022-09-19 08:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20220919_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 58, 7, 850341)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 12, 58, 7, 850341)),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 58, 7, 856355)),
        ),
    ]
