# Generated by Django 3.2.15 on 2022-09-19 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20220919_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 13, 5, 22, 804373)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 13, 5, 22, 804373)),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 13, 5, 22, 811130)),
        ),
    ]
