# Generated by Django 3.2.15 on 2022-09-22 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20220921_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 13, 6, 51, 355563)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 13, 6, 51, 355563)),
        ),
        migrations.AlterField(
            model_name='installation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='link_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkdetails'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='pppoe_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='installation',
            name='pppoe_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='installation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.task', unique=True),
        ),
        migrations.AlterField(
            model_name='linkdetails',
            name='installation_date',
            field=models.DateTimeField(),
        ),
    ]
