# Generated by Django 3.2.15 on 2022-09-24 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20220922_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelocation',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='changelocation',
            name='link_details',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='link_details',
        ),
        migrations.RemoveField(
            model_name='troubleshoot',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='troubleshoot',
            name='link_details',
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.task', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkdetails',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.task', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changelocation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.task', unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 16, 24, 7, 724169)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 16, 24, 7, 724169)),
        ),
        migrations.AlterField(
            model_name='onlinesupport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.task', unique=True),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.task', unique=True),
        ),
    ]
