# Generated by Django 3.2.15 on 2022-09-28 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20220926_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 26, 53, 674544)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 15, 26, 53, 674544)),
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('referral', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 26, 53, 669261))),
                ('activation', models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 26, 53, 669289))),
                ('valid', models.DateTimeField(default=datetime.datetime(2023, 9, 28, 15, 26, 53, 669308))),
                ('note', models.TextField(blank=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contracttypes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contractstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('Lease_amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('collected', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contracts')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.router')),
            ],
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_total', models.IntegerField(default=0)),
                ('service_charge', models.IntegerField(default=0)),
                ('other_charges', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('lease_deposit', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contracts')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contractcurrency')),
            ],
        ),
        migrations.CreateModel(
            name='ContractPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contracts')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.package')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAntenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('Lease_amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('collected', models.BooleanField(default=False)),
                ('antenna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.antenna')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contracts')),
            ],
        ),
    ]
