# Generated by Django 3.2.15 on 2022-09-28 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20220928_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 56, 4, 282091)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 15, 56, 4, 282091)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='activation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 56, 4, 276052)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 56, 4, 276024)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 15, 56, 4, 276071)),
        ),
        migrations.AlterField(
            model_name='router',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
